#!/usr/bin/env bash
# Installs Nginx and config
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Holberton School' > /var/www/html/index.html
sudo service nginx start
