#!/usr/bin/env bash
#Write a Bash script that displays a list of currently running processes.
#-f Full-format listing
#-a show process for all usersç
#-u display process user/owner
#-x must have a tty
ps -faux
