#!/usr/bin/env bash
#script display "Holberton School" 10 times, hi in 9th iteration

i=0

while [ $i -lt 10 ]
do
    if [ $i -eq 9 ]
    then
	echo 'Hi'
    fi
    echo "Holberton School"
    (( i++ ))
done
