#!/usr/bin/env bash
#script dfisplay "Holberton School" 10 times but 8 gl 4 bl

i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 3 ]
    then
	echo 'bad luck'
    elif [ $i -eq 7 ]
    then
	echo 'good luck'
    else
	echo 'Holberton School'
    fi
    (( i++ ))
done
