#!/usr/bin/env bash
#script display hours and minutes everyday

hh=0
while [ $hh -le 12 ]
do
    echo "Hour: $hh"
    mm=1
    while [ $mm -le 59 ]
    do
	echo "$mm"
	(( mm++ ))
    done
    (( hh++ ))
done
